produits:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter }
supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimer }

livraison:
    path:     /panier/livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /panier/validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:categorie }

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:recherche }




