# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.form_login_authenticator:
    class: AppBundle\Security\FormLoginAuthenticator
    arguments: ["@router", "@security.password_encoder"]


  app.api_token_authenticator:
    class: AppBundle\Security\ApiTokenAuthenticator
    arguments: ["@app.api_user_repository"]

  app.api_user_repository:
    class: AppBundle\Repository\ApiUserRepository
    factory: [ "@doctrine.orm.default_entity_manager", getRepository ]
    arguments: [AppBundle:ApiUser]


