adminclients:
    resource: "@AppBundle/Resources/config/routing/clients.yml"
    prefix:   /admin/clients

dashboard:
    path:     /dashboard
    defaults: { _controller: AppBundle:User:dashboard }

login:
    path:    /login
    defaults: { _controller: AppBundle:Security:login}

