<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * UsersAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAdressesRepository extends \Doctrine\ORM\EntityRepository
{
}
